backend:
  name: git-gateway # Usar Git Gateway para conectar al repositorio
  branch: main # La rama donde se guardarán los cambios

media_folder: static/img # Carpeta donde se subirán las imágenes
public_folder: /img # Carpeta pública para las imágenes

media_library:
  name: git-gateway # Usar Git Gateway para la biblioteca de medios
  config:
    folder: 'assets/img' # Carpeta donde se guardan las imágenes
    public_folder: '/img' # Carpeta pública para acceder a las imágenes

collections:
  - name: "posts" # Nombre interno de la colección
    label: "Posts" # Etiqueta visible para la colección
    folder: "blog/posts" # Carpeta donde se guardarán los posts
    create: true # Permitir la creación de nuevos posts
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Formato del slug
    fields:
      - { label: "Title", name: "title", widget: "string" } # Campo para el título
      - { label: "Publish Date", name: "date", widget: "datetime" } # Campo para la fecha de publicación
      - { label: "Body", name: "body", widget: "markdown" } # Campo para el contenido en Markdown

